### ISSUE TITLE
Feature: User can input a purchase

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#1]
## ⚙️ Feature

User can input a purchase

## 📐 Functionality

User can input a purchase type (deposit or expense), a date, a spending category, a comment, and a payment method.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/142969090-d1d29e6a-c914-43c1-9dff-88540df11d97.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] create header component
- [x] create footer 
- [x] create slide-out menu
- [x] create Expense | Deposit component
- [x] create new entry form

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Create POST endpoint at `api/entry` to save a new `deposit` or `expense`
- [x] Create `ClientError` class
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
