### ISSUE TITLE
Feature: User can see a categorical breakdown of their spending

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#10]
## ⚙️ Feature

User can see a categorical breakdown of their spending.

## 📐 Functionality

User can select `By Category` form the `categories` dropdown component to reveal a `doughnut` chart depicting a categorical breakdown of their spending

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/143170025-e85b9f08-4e02-445b-af9d-70ec889be3c8.png)

## ✅ Task List

- [ ] add `if/else` statement to `chart` component that generates `combo-line-bar` graph or `doughnut` chart depending on the value of `categories` dropdown 

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
