### ISSUE TITLE
Feature: User can edit a purchase

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#2]
## ⚙️ Feature

User can edit a purchase

## 📐 Functionality

User will be able to access a table of purchases, choose a purchase, and edit that purchase

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/142970088-275a3a04-1695-4de8-96fa-23c3b420cec2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] apply header, menu and footer
- [x] add indicator circle to footer
- [x] add page indicator icon to header
- [x] add create icon to header
- [x] make entry component
- [x] make table component

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] create `PATCH` req endpoint to `/api/entry/$Id`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
