### ISSUE TITLE
Feature: User can delete a purchase

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#3]
## ⚙️ Feature

User can delete a purchase

## 📐 Functionality

User will be able to view a table of entries, choose an individual entry and delete it.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/75178406/142970777-e4542e70-d9ac-42cb-af49-1019fabf0b34.png)
![image](https://user-images.githubusercontent.com/75178406/142970791-1c0d3ba2-e420-422a-914a-7f82798769e3.png)

## ✅ Task List

- [x] make delete modal
- [x] input entry data into delete modal
- [x] submit `delete` request to database

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] add `DELETE` req endpoint to `/api/entry/$Id` to delete past purchase
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
