### ISSUE TITLE
Feature: User can insert a past purchase

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#4]
## ⚙️ Feature

User can insert a past purchase

## 📐 Functionality

The user will be able to click on a `create new purchase` icon to insert a past purchase.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/142971355-303ed75a-9598-4a4f-bc91-b7515a30aa37.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] add `showEntryFormModal( )` function to `onClick` event listener on create icon

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
