### ISSUE TITLE
Feature: User can input a monthly budget

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#5]
## ⚙️ Feature

User can input a monthly budget

## 📐 Functionality

The user will be able to access a menu of `Account Settings` options. From this menu, the user will be able to choose an option to enter a monthly budget that will appear in analytics (elsewhere in the app). 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/142972291-a4c0cb9d-d695-4d2e-9183-90c7f2a7e17f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ]  add header with page indicator
- [ ] create account settings button component
- [ ] create `set your budget`, `manage payment methods`, and `manage spending categories`
- [ ] add functions to buttons

- on Set Your Budget page

- [ ] add set your budget page indicator
- [ ] add Weekly | Monthly | Yearly component
- [ ] add enter your budget input
- [ ] add budget display component 

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] add `PATCH` endpoint to `/api/users/budget`
- [ ] add `POST` endpoint to `/api/users/budget`
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
