### ISSUE TITLE
Feature: User can input a payment method

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#6]
## ⚙️ Feature

User can input a payment method

## 📐 Functionality

User can access a table of their payment methods. From the table of payment methods, the user can add a new payment method

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/142975057-d317a303-fa0a-4fba-ac53-0d917695b190.png)

## ✅ Task List

- [ ] reuse `expense` table as template for payment method table
- [ ] make `paymentModal`
- [ ] add `create` icon to header that links to `showNewPaymentModal( )`

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] add `POST` req endpoint to `/api/payment`
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
