### ISSUE TITLE
Feature: User can add a spending category

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#7]
## ⚙️ Feature

User can add a spending category

## 📐 Functionality

The user will be able to access a table where all payment methods are listed. The user will be able to click on an icon which shows a modal. The user can then add a spending category. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/143160353-a0c05d45-b069-4787-8db3-112f9d3405c4.png)

## ✅ Task List

- [ ] use `table` component to make table of payment methods (`fetch` req to `paymentMethods` database)
- [ ] add `create` icon to header
- [ ] add `onClick` event listener to `create` icon
- [ ] use `new payment method` modal as template to make `new spending category` modal

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
