### ISSUE TITLE
Feature: User can see a summary of their spending 

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#8]
## ⚙️ Feature

User can see a summary of their spending 

## 📐 Functionality

The user will be able to click a button on the main menu and be directed to a page that displays a radial gauge chart and various financial summary statistics. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/143163865-a784763d-4455-4737-a3fe-2a58c7247ea8.png)

## ✅ Task List

- [ ] query `db` for budget, payment methods and spending categories
- [ ] create `radialGauge` component
- [ ] create `quickView` component w/ `radialGauge` component and summary statistics

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
