### ISSUE TITLE
Feature: User can see a graph of their spending

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/quick-track#9]
## ⚙️ Feature

User can see a graph of their spending

## 📐 Functionality

Users will be able to toggle between the options `weekly`, `monthly`, or `yearly` spending and see a `combo-line-bar` chart of their spending. The graph will show the appropriate budget (graphed as a line), their daily spending (as bars), and their total spending (graphed as a line)

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/75178406/143166934-58bb48cb-61c0-478f-bbbd-cfe14d5a2c4f.png)

## ✅ Task List

- [ ] make `categories` dropdown component with `Quick View`, `All Categories`, `By Category`, and user's spending categories
- [ ] make `timeframe` dropdown component with options `week`, `month`, and `year`
- [ ] make `clarifying` dropdown component with options that range based on the `timeframe selection`
- [ ] add chart component
- [ ] add `spending statistics` component
- [ ] add block component that allows the addition/subtraction of spending statistics

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
